name: BC

on:
  workflow_call:
    inputs:
      php:
        description: PHP versions to test, separated by comma.
        default: >-
          ['8.1']
        required: false
        type: string
      tools:
        description: Tools to test, separated by comma.
        default: "composer:v2"
        required: false
        type: string

jobs:
  bc:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    name: "Backward Compatibility Check"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ inputs.tools }}

      - name: Install roave/backward-compatibility-check
        run: composer require --dev roave/backward-compatibility-check

      - name: Run roave/backward-compatibility-check
        run: vendor/bin/roave-backward-compatibility-check --format=github-actions
